### ISSUE TITLE
new sub-release?

### ISSUE THREAD

**Issue by olesenm** [KaHIP/KaHIP#101]
Are there enough incremental changes to warrant bumping to v3.12 ? Was thinking of updating the OpenFOAM ThirdParty for the upcoming Dec release (OpenFOAM-v2112) and wanted to get a heads-up so that we can start testing (or not).

**Comment by schulzchristian** [comment]
will do soon (within the next week).

**Comment by olesenm** [comment]
nice - thanks.

**Comment by schulzchristian** [comment]
there is a new release now.

Best
Christian

**Comment by olesenm** [comment]
Got it - thanks.
