### ISSUE TITLE
Is there any requirement on the input graph?

### ISSUE THREAD

**Issue by VoVAllen** [KaHIP/KaHIP#104]
Can the input graph contain multi edges between single pair of nodes? Can the graph be non-bidirected? (Directed graph that some edges don't have reverse edges) Can the graph have self-loop?

Also is the answer here also applied to mt-Kahip? 

Thanks!

**Comment by schulzchristian** [comment]
Hi,

please have a look into the manual.

- Multiple (parallel) edges are not allowed
- non-bidirected is not allowed
- self-loops are not allowed.

Best
Christian
