### ISSUE TITLE
CMake Error: The source directory ".../KaHIP/build" does not appear to contain CMakeLists.txt

### ISSUE THREAD

**Issue by emamajanyan** [KaHIP/KaHIP#109]
Hi,

After the recent [commit 3f7071e4e](https://github.com/KaHIP/KaHIP/commit/328404fe73b272d7b4810c731c5f94aeb8a4b3c9) update the compile_withcmake.sh fails with the mentioned error.
The error happens when the "ADDITIONAL_ARGS" is empty (no option specified via $1 to the script).

`./compile_withcmake.sh` 

which is the same as 

```
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release ""
```
no error in case
`./compile_withcmake.sh BUILDPYTHONMODULE
`

The previous(below) version where the -B and -S were specified works without any issue.
```
mkdir build
cmake -B build/ -S . -DCMAKE_BUILD_TYPE=Release ""
```

cmake version 3.22.0

**Comment by DanielSeemaier** [comment]
Sorry! That really shouldn't have happened. 

Does it work for you now? 

I will setup a Github runner to prevent this kind of mistakes in the future.

**Comment by emamajanyan** [comment]
Yes, it works. Thanks for quick response & fix.
