### ISSUE TITLE
Undefined reference to 'METIS_SetDefaultOptions'

### ISSUE THREAD

**Issue by SonglinLife** [KaHIP/KaHIP#115]
Hi, 
I can't compile my CPP project when using the KaHIP, but I have already linked the kahip lib in cmakelists.txt.
> target_link_libraries(SSD_Based_Plan libkahip.a)

😭 I have read the manual, but cant fix it.
the error message 
> --target all --
[build] [1/1   0% :: 0.000] Re-running CMake...
[build] -- Configuring done
[build] -- Generating done
[build] -- Build files have been written to: /data/wsl/SSD_Based_Plan/build
[build] [1/2  50% :: 1.845] Building CXX object CMakeFiles/SSD_Based_Plan.dir/main.cpp.o
[build] [2/2 100% :: 1.941] Linking CXX executable SSD_Based_Plan
[build] FAILED: SSD_Based_Plan 
[build] : && /usr/bin/g++  -fopenmp -O3 -DNDEBUG   CMakeFiles/SSD_Based_Plan.dir/main.cpp.o  -o SSD_Based_Plan -L/data/wsl/SSD_Based_Plan/KaHIP/deploy   -L/usr/local/lib -Wl,-rpath,/data/wsl/SSD_Based_Plan/KaHIP/deploy:/usr/local/lib  -lmetis  -Wl,-Bstatic  -lGKlib  -lkahip  -Wl,-Bdynamic && :
[build] /usr/bin/ld: /data/wsl/SSD_Based_Plan/KaHIP/deploy/libkahip.a(kaHIP_interface.cpp.o): in function `reduced_nd_fast':
[build] kaHIP_interface.cpp:(.text+0x268a): undefined reference to `METIS_SetDefaultOptions'
[build] /usr/bin/ld: kaHIP_interface.cpp:(.text+0x26b6): undefined reference to `METIS_NodeND'
[build] collect2: error: ld returned 1 exit status
[build] ninja: build stopped: subcommand failed.
[build] Build finished with exit code 1

**Comment by schulzchristian** [comment]
my best guess is you have METIS installed on your system. In this case, you also need to link against the metis library.
