### ISSUE TITLE
make fails, with or without -DPARHIP=Off

### ISSUE THREAD

**Issue by rbelew** [KaHIP/KaHIP#125]
(AppleClang 14)

there is some part of the cmake/make sequence i'm not appreciating.

"If you don't want to run ParHIP, you can easily get rid of this dependency." made me look at #56 and I used the `-DPARHIP=Off` parameter, and worked a bit better.

but i am still getting these errors:
```
.../KaHIP/extern/argtable3-3.2.1/argtable3.c:3595:104: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
TREX_API TRex* trex_compile(const TRexChar* pattern, const TRexChar** error, int flags) __attribute__((optimize(0)));
^~~~~~~~~~~
1 warning generated.
[ 56%] Built target libkaffpa
[ 57%] Building CXX object CMakeFiles/libkaffpa_parallel.dir/lib/parallel_mh/parallel_mh_async.cpp.o
.../KaHIP/lib/parallel_mh/parallel_mh_async.cpp:11:10: fatal error: 'mpi.h' file not found
#include <mpi.h>
^~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/libkaffpa_parallel.dir/lib/parallel_mh/parallel_mh_async.cpp.o] Error 1
make[1]: *** [CMakeFiles/libkaffpa_parallel.dir/all] Error 2
make: *** [all] Error 2
```
any ideas why I'd be having this issue when so many others seem to do much better?!

**Comment by schulzchristian** [comment]
it looks like you don't have MPI installed.

Best
Christian

**Comment by rbelew** [comment]
hi, thanks Cristian!  Correct, but I took your comment "If you don't want to run ParHIP, you can easily get rid of this dependency" to mean that it is not necessary?

**Comment by DanielSeemaier** [comment]
the evolutionary partitioner (kaffpaE) also depends on MPI, hence the failure

should we just disable the target if MPI could not be found? #126 would do that, if you are fine with it @schulzchristian

**Comment by schulzchristian** [comment]
Maybe a NOMPI option to disable targets that need MPI? Otherwise parhip and kaffpae may not be installed and the user does not know why.

**Comment by rbelew** [comment]
i've now installed MPI, and cmake finds it

```
-- Found MPI: TRUE (found version "3.1")  
MPI detected (can use MPI_HOME hint to direct the detection...)
-- MPI include: /Users/rik/data/pkg/miniconda3/condabin/include
-- MPI library: /Users/rik/data/pkg/miniconda3/condabin/lib/libmpi.dylib
```

but now it cannot find `metis.h`:

```
/Users/rik/data/git/KaHIP/interface/kaHIP_interface.cpp:12:18: fatal error: 'metis.h' file not found
        #include "metis.h"
                 ^~~~~~~~~
```

**Comment by DanielSeemaier** [comment]
I think that this is because `find_library()` finds the Metis library somewhere on your system (i.e., a file called libmetis.{a,so} in some of your library directories), but the compiler does not find the Metis header in any of its default include dirs. Not entirely sure, but I think that this might be a problem with your setup. 

Do you have the library installed? 
If not, you could use `--debug-find`, i.e., `cmake -B build --debug-find` from the KaHIP directory to find out from where it picks up the library.
If you do expect it to find Metis, could you double check whether the header file is in any of your default include dirs (and, if not, move it there or add the right path to your `CPLUS_INCLUDE_PATH` env variable)?

**Comment by rbelew** [comment]
i do have metis installed.  i copied the installed `metis.h` to `.../KaHIP/lib/metis.h` and it's now found!

it is still throwing this error twice:

```
.../KaHIP/extern/argtable3-3.2.1/argtable3.c:3595:104: warning: unknown attribute 'optimize' ignored [-Wunknown-attributes]
TREX_API TRex* trex_compile(const TRexChar* pattern, const TRexChar** error, int flags) __attribute__((optimize(0)));
                                                                                                       ^~~~~~~~~~~
```

but the build seems to complete succesfully!

**Comment by DanielSeemaier** [comment]
great! the error is just a warning which seems to be fixed in the latest argtable version (which is now included in KaHIP)

**Comment by rbelew** [comment]
great, then all bits resolved and i'm closing this issue.  thanks very much @DanielSeemaier for your responsiveness!
