### ISSUE TITLE
Does every block is connected? 

### ISSUE THREAD

**Issue by WILLCHEN05** [KaHIP/KaHIP#150]
Hi,

Is there a partitioner in this project which can garuntee to output connected block? It is a very important constraint in my problem.

Thanks for your reply.
Chen.

**Comment by schulzchristian** [comment]
Hi,

currently there is no such algorithm in KaHIP. However, there is an option
in kaffpaE to make it more likely to output such a partition. On the other
hand you can always make a partition connected using a postprocessing step.

Best
Christian

**Comment by WILLCHEN05** [comment]
Hi Christian,

Thanks for your reply.
May I ask which option in kaffpaE are you referring to？Since I have to output a given number of partitions, I can not use a postprocessing step because it will change the number of partitions.

Best
Chen

**Comment by schulzchristian** [comment]
sorry, I just saw that we don't have it in the public release. I can share a version that has this option with you if you are interested. Just send me an email (christian.schulz@informatik.uni-heidelberg.de). Thanks
