### ISSUE TITLE
Edges counted twice?

### ISSUE THREAD

**Issue by jaravad** [KaHIP/KaHIP#50]
Hi, I was partitioning a graph using the following command:

`./deploy/kaffpa examples/delaunay_n15.graph --k 6554 --preconfiguration=fast`

In the output there is a line that says:

`graph has 32768 nodes and 196548 edges`

I don't understand why it's showing 196548 edges, the graph file I'm using has half the edges: 98274

**Comment by schulzchristian** [comment]
Hey,

the Metis file contains the number of undirected edges. Internally we store
a forward and backward edge for each undirected edge. Hence, the number.

Hope this helps :)

Best
Christian

**Comment by jaravad** [comment]
Ohh I see, thank you. I was wondering if I can do a partitioning time comparison between Kaffpa and Metis, do you think are they comparable?

**Comment by schulzchristian** [comment]
It really depends on what you want to achieve. High quality is not for
free. Depending on the structure of the graphs fast configurations of KaHIP
can be faster than Metis. Please have a look at the papers mentioned in the
README (all of them are freely available on arxiv) for detailed
experimental studies.

Best
Christian

**Comment by jaravad** [comment]
Okay, thank you so much for the help
