### ISSUE TITLE
Documentation: Is the install documentation out of date?

### ISSUE THREAD

**Issue by jlabeit** [KaHIP/KaHIP#51]
In the READE.md it states that by running
-  `./compile.sh` everything is built and
- `./deploy/kaffpa examples/delaunay_n15.graph --k 2 --preconfiguration=strong` can be used to run an example

However, `compile.sh` only exists in the bundle downloadable from [here](http://algo2.iti.kit.edu/schulz/software_releases/KaHIP_2.12.tar.gz).

**Comment by schulzchristian** [comment]
Hi Julian,

 Thanks for the remarks. For the release it should be fine. The master
branch is not fully up to date. In the next week or two I will also
integrate most pull requests and also fix this issue (the readme will be
extended quite a bit).

Best regards
Christian

**Comment by jlabeit** [comment]
HI Christian,

thanks for the quick feedback. Then I'll use the [released version](http://algo2.iti.kit.edu/schulz/software_releases/KaHIP_2.12.tar.gz) and keep this issue open for future reference. 

Regards,

Julian

**Comment by schulzchristian** [comment]
did quick fix now. thanks again!
