### ISSUE TITLE
Tag for version 2.12 is missing

### ISSUE THREAD

**Issue by TEFEdotCC** [KaHIP/KaHIP#55]
Hello,

I think a few weeks ago it was possible to get version 2.12 from master branch.
Also OpenFOAM (https://develop.openfoam.com/Development/ThirdParty-common/-/blob/master/SOURCES.txt) are reference to version 2.12.

Where is the version 2.12 sources to download?

**Comment by schulzchristian** [comment]
Hey,

you can find it here algo2.iti.kit.edu/schulz/software_releases/KaHIP_2.12.tar.gz

Best
Christian

p.s. sorry there is no tag for 2.12

**Comment by TEFEdotCC** [comment]
of course, but why no tag in git repository for version 2.12?

**Comment by TEFEdotCC** [comment]
why I will an tag?

I build container images for openfoam and some other applications. So, currently I use as possible git repositories with tag to get the source and all the shit was it needed.

**Comment by schulzchristian** [comment]
Hi Thomas, 

the functionality that you are using through OpenFOAM is unchanged in the current release (and master branch), why don't you just use the new master branch if you got KaHIP from there before or from the new release tag?

Best
Christian

**Comment by TEFEdotCC** [comment]
I used the master branch a few month ago, as it pointed to v2.12.
Actually I have got an build issue (linking error to KaHIP).
And with my mind / thinking a "major version change" has changing's there are not compatible for code that offical use a older version. 

**Git is a version managment software. Why do you not use this capability?**
Tag an offical release, ... opening an maintenance branch, ... and so on

So, one of many build/link errors (mostly looks the same) with **actually master branch**
(I know the build issues are problems of OpenFOAM, but to tag an 2.12 version here is your problem)
```console
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `nested_dissection::ordering() const'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `nested_dissection::perform_nested_dissection(PartitionConfig&)'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `nested_dissection::nested_dissection(graph_access*)'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `mapping_algorithms::construct_a_mapping(PartitionConfig&, graph_access&, matrix&, std::vector<unsigned int, std::allocator<unsigned int> >&)'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `mapping_algorithms::mapping_algorithms()'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `mapping_algorithms::~mapping_algorithms()'
```

**Comment by schulzchristian** [comment]
Hi Thomas,

thanks for the input, will fix the linking errors tomorrow.
Meanwhile, you can also use github to pull 2.10 from here https://github.com/KaHIP/KaHIP/tree/357bebb13e0384b80a191eb3af0dbed2cde536db

Best
Christian

**Comment by TEFEdotCC** [comment]
Thanks for your fast reply's (really fast).

**Comment by schulzchristian** [comment]
I just had a look, I am actually not building libkahip.so myself  ...
I am building the shared library libinterface.so and the static one libinterface.a (the static one is rename to libkahip.a in deploy, the shared one is not copied atm when using the build bash script). Both of them contain the mapping and node ordering symbols. Not sure where this is coming from, but you should link against libinterface.so. Could you tell me which OpenFOAM repo/version you are using so I can have a look? 

Best
Christian

p.s. regarding the tag, i will see how i can create a release tag from an old commit, but this may take a day or two

**Comment by schulzchristian** [comment]
Okay, there is now a release tag for v2.12.

All the best
Christian

**Comment by TEFEdotCC** [comment]
I use OpenFOAM from openfoam.com. OpenFOAM++ in the past.
```console
OF_GIT_URL="https://develop.openfoam.com/Development/openfoam.git"
OF_TP_GIT_URL="https://develop.openfoam.com/Development/ThirdParty-common.git"
```
The v2006 version naming for kahip is "kahip-$Version".
I use ubuntu:20.04 (I had my self, why do not use centos:8 :D That makes some dependices simpler ).

Link to my [buildah script](https://cloud.thomas-enzinger.de/s/9Kmoy66HzJoLxwp)

**Comment by TEFEdotCC** [comment]
And thank you much for the tag.
I test it tommorw evening.
Climbing with the my wife has a higher priority in the next 24 hours ;-)

**Comment by TEFEdotCC** [comment]
Your taged "2.12" version does also not work :(
Seems the symbols does not exist

- The taged version "2.12" in git repository **is different** to the offical release tar archive.
- Also build error in taged 2.12 git version

```console
...
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `nested_dissection::ordering() const'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `nested_dissection::perform_nested_dissection(PartitionConfig&)'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `nested_dissection::nested_dissection(graph_access*)'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `mapping_algorithms::construct_a_mapping(PartitionConfig&, graph_access&, matrix&, std::vector<unsigned int, std::allocator<unsigned int> >&)'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `mapping_algorithms::mapping_algorithms()'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `mapping_algorithms::~mapping_algorithms()'
collect2: error: ld returned 1 exit status

...
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `nested_dissection::ordering() const'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `nested_dissection::perform_nested_dissection(PartitionConfig&)'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `nested_dissection::nested_dissection(graph_access*)'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `mapping_algorithms::construct_a_mapping(PartitionConfig&, graph_access&, matrix&, std::vector<unsigned int, std::allocator<unsigned int> >&)'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `mapping_algorithms::mapping_algorithms()'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `mapping_algorithms::~mapping_algorithms()'
collect2: error: ld returned 1 exit status
make[2]: *** [/opt/OpenFOAM/OpenFOAM-latest/wmake/makefiles/general:150: /opt/OpenFOAM/OpenFOAM-latest/platforms/linux64GccDPInt32Opt/bin/snappyHexMesh] Error 1
make[1]: *** [/opt/OpenFOAM/OpenFOAM-latest/wmake/makefiles/apps:29: generation] Err

...
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `nested_dissection::ordering() const'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `nested_dissection::perform_nested_dissection(PartitionConfig&)'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `nested_dissection::nested_dissection(graph_access*)'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `mapping_algorithms::construct_a_mapping(PartitionConfig&, graph_access&, matrix&, std::vector<unsigned int, std::allocator<unsigned int> >&)'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `mapping_algorithms::mapping_algorithms()'
/usr/bin/ld: /opt/OpenFOAM/OpenFOAM-latest/ThirdParty/platforms/linux64GccDPInt32/lib/libkahip.so: undefined reference to `mapping_algorithms::~mapping_algorithms()'
collect2: error: ld returned 1 exit status
```

Is that a problem with the SCons scripts?
In the offical release there are one `bash compile.sh` and `SConstruct` + `Sconscript` in the root directory.

**Comment by schulzchristian** [comment]
Are you using the correct kahip interface? The symbols you are missing are symbols that have been added with the last release. They are also contained in the interface of that tag. So i am not sure if the problem is ok this side.

Best
Christian

**Comment by DanielSeemaier** [comment]
Hey, if I'm not mistaken, the exact v2.12 version bundled with OpenFOAM is ad07d2d (not 5c275e1)

ad07d2d still includes the scons scripts, so it's probably worth getting this right

**Comment by schulzchristian** [comment]
Thanks Daniel!
v2.12 is now pointing to that commit. 
Thomas: can you check if you still have any problems?

**Comment by schulzchristian** [comment]
Did you at some point call make install and are now linking and including the wrong files?

**Comment by TEFEdotCC** [comment]
Hallo Christian und Daniel,

zur erst bitte ich um Verständnis für die deutlich verstätete Antwort, welche sich Aufgrund einer kirchlichen Hochzeit in den Bergen, unter einem Kreuz im Freiem.

Ich überprüfe dies sofort und werde die Nachricht morgen entsprechend abändern.
