### ISSUE TITLE
Unbalanced partitions with `global_multisection` (and `process_mapping`)

### ISSUE THREAD

**Issue by cwpearson** [KaHIP/KaHIP#61]
Using `global_multisection` with `--enforce_balance` yields unbalanced partitions.

I'm using the following graph file:

```
$ cat test.graph
4 6 1
2 5 3 5 4 5
1 5 3 6 4 5
1 5 2 6 4 4
1 5 2 5 3 4
```

corresponding to the following dense matrix:

```
0 5 5 5 
5 0 6 5 
5 6 0 4 
5 5 4 0
```
The command I am running is

```
$ ./global_multisection test.graph --hierarchy_parameter_string 2:2 --distance_parameter_string 1:10 --preconfiguration=eco --enforce_balance
io time: 5.19753e-05
graph has 4 nodes and 12 edges
performing partitioning! overall k=4
multisectioning took 0.00352097
performing additional 1-to-1 mapping!
communication graph has 4 nodes and 6 edges 
number of processors is a power of two, so no mapping algorithm is performed (identity is best)
time spent for mapping 0
cut             24
bnd             4
balance         2
max_comm_vol    4
quadratic assignment objective J(C,D,Pi') = 300
writing partition to tmppartition4 ...
```

```
$ cat tmppartition4
0
1
1
2
```

Here, I expect some permutation of `0,1,2,3`, but instead, two vertices are placed in partition `1` a nd none in partition `3`.

**Comment by schulzchristian** [comment]
Hi Carl,

Enforce balance only works for unweigthed graphs (due to the balancing
models used) :)

Best
Christian

**Comment by cwpearson** [comment]
Thanks for the clarification, Christian! Perhaps the user guide sections for `global_multisection` and `process_mapping` could be updated to say that. I see now in the example (misc/example_library_call/interface_test.cpp`) that the adjcwgts argument is `NULL`, if that is required it would be helpful for the documentation to reflect it.

I modified my graph file to be unweighted:

```
4 6
2 3 4
1 3 4
1 2 4
1 2 3
```

which yields similar unbalanced results:

```
1
0
1
2
```

**Comment by schulzchristian** [comment]
Hi Carl,

could you tell me the precise CLI call that you used?

Thanks
Christian

**Comment by cwpearson** [comment]
Christian,

I am on commit 08f58b193cd13fad2a7123eb353a891fd570446d (tip of master right now).

The CLI is

```
./global_multisection ../test.graph --hierarchy_parameter_string 2:2 --distance_parameter_string 1:10 --preconfiguration=eco --enforce_balance
```

The contents of `../test.graph` are
```
4 6
2 3 4
1 3 4
1 2 4
1 2 3
```

During execution, the following is printed on the console:
```
io time: 4.60148e-05
graph has 4 nodes and 12 edges
performing partitioning! overall k=4
multisectioning took 0.000536203
performing additional 1-to-1 mapping!
communication graph has 4 nodes and 6 edges 
number of processors is a power of two, so no mapping algorithm is performed (identity is best)
time spent for mapping 0
cut             5
bnd             4
balance         2
max_comm_vol    4
quadratic assignment objective J(C,D,Pi') = 64
writing partition to tmppartition4 ... 
```

the contents of `tmppartition4` after the execution are
```
1
0
1
2
```

**Comment by schulzchristian** [comment]
ah I see where the problem is. Enforce balance atm does not run after global section, I added it.
Could you try?

**Comment by cwpearson** [comment]
Looks good! Is the same change valid in `process_mapping`? If you'd like, I can make a PR with that.

**Comment by schulzchristian** [comment]
which app do you mean? the way this works in the released code is:
compute a parition using kaffpa or global_multisection and then afterwards perform one to one mapping on the quotient graph. We also have n-to-1 process mapping algorithms (by marcelo fonseca faraj), they are not yet publicly release but we could send you a copy -- just send me an email.

Best
Christian

**Comment by cwpearson** [comment]
I mean in the interface, not in any of the apps: https://github.com/KaHIP/KaHIP/blob/master/interface/kaHIP_interface.cpp#L502-L583

It seems like `internal_processmapping_call` largely mirrors `global_multisection`. Ultimately, I'd like to use KaHIP as a library to do this placement, but the `process_mapping` interface was delivering the same unbalanced partitions as `global_multisection` did. Can the same fix that you applied to `global_multisection` be done in `internal_processmapping_call` as well?

**Comment by schulzchristian** [comment]
thanks for the clarification. yes the same fix should work. If you issue a pull request I will directly merge it.

Thanks
Christian

**Comment by cwpearson** [comment]
Hi, I made a PR: https://github.com/KaHIP/KaHIP/pull/62

Please be aware that I am not versed enough in the algorithm to know whether my modifications have broken it. Hope it's useful and does the right thing!
