### ISSUE TITLE
Error compiling the program

### ISSUE THREAD

**Issue by JiaweiChenKodomo** [KaHIP/KaHIP#68]
I got the following error when running `sh ./compile-withcmake.sh` in the KaHIP directory:

> CMake Error in /home/user_name/workspace/KaHIP/build/CMakeFiles/CMakeTmp/CMakeLists.txt:
>   Imported target "MPI::MPI_C" includes non-existent path
> 
>     "/home/user_name/workspace/KaHIP/'/opt/intel/oneapi/mpi/2021.1.1/include'"
> 
>   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
> 
>   * The path was deleted, renamed, or moved to another location.
> 
>   * An install or uninstall procedure did not complete successfully.
> 
>   * The installation package was faulty and references files it does not
>   provide.

What could be my problem here?  

I have installed Intel MKL after I installed cmake. Is this what caused the problem? (I have runned the setvars.sh of the MKL to set up the variables each time.)

I am using an Ubuntu 20.04 system.

**Comment by schulzchristian** [comment]
Hey,

not sure. KaHIP does not need MKL.
It looks to me like your mpi installation is broken.

Best
Christian
