### ISSUE TITLE
-march=native breaks portability of KaHIP within docker containers

### ISSUE THREAD

**Issue by IgorBaratta** [KaHIP/KaHIP#69]
KaHIP is crashing with illegal hardware instruction errors on some docker images.

This is mainly because `-march=native`  is enabled by default, however, the docker images are not generally built in the same machine as the containers. 
In my specific case, the docker image is built on a server using docker hub and then used for CI with GitHub actions.

A possible solution is to enable optimizations and `-march=native` only on Release mode. 
If you feel that it's a sensible solution, I can make a PR.

Alternatively,  I'd suggest to remove all aggressive compile flags in the cmake file, and instruct the users in the README.md about ‘recommended settings’ (via `-DCMAKE_CXX_FLAGS=`).

**Comment by schulzchristian** [comment]
Hi Igor,

would it help you if we add a flag to disable native optimizations? This would be better as most people dont have to think about optimization flags...

Best
Christian

**Comment by IgorBaratta** [comment]
Hi Christian,

Sure, that would definitely help.

**Comment by schulzchristian** [comment]
Ok, i will try to integrate such a flag tomorrow.

Best
Christian

**Comment by IgorBaratta** [comment]
Thanks. I really appreciate it.

**Comment by schulzchristian** [comment]
Absolutely no problem :)

**Comment by schulzchristian** [comment]
Hi Igor, 

you should be able to use the flag -DNONATIVEOPTIMIZATIONS=On now.

Best
Christian
