### ISSUE TITLE
ILP exact solver segfaults on Gurobi exception

### ISSUE THREAD

**Issue by hay-k** [KaHIP/KaHIP#70]
`ilp_exact` and `ilp_improve` terminate with segmentation fault when Gurobi throws exception and do not print the exception message properly. 

**How to reproduce:**
Setup Gurobi in a way that it is not possible to call `GRBEnv()` without exception. E.g. install Gurobi, but do not install the Gurobi license. If you already have Gurobi installation with license, you can achieve this by setting the `GRB_LICENSE_FILE` environment variable to something which is not a Gurobi license file (e.g. `export GRB_LICENSE_FILE=/dev/null`). In this case when calling `GRBEnv()` a license exception will be thrown which will make the tools to segfault.
```
terminate called after throwing an instance of 'GRBException'
Aborted (core dumped)
```

**Solution:**
The reason behind this issue is the way the Gurobi exceptions are handled in the try-catch block of `lib/ilp_improve/ilp_exact.h` and `lib/ilp_improve/ilp_improve.h`. There are the following lines in the catch block
```
catch(GRBException e) {
            GRBEnv* env = new GRBEnv();
            GRBModel model = GRBModel(*env);
            std::cout << e.getErrorCode() << " Message: " << e.getMessage() << std::endl;
            return model;
}
```
Before printing the error message in the catch block, the code tries to initialize an empty Gurobi environment, which again throws the same exception as it did in the try block. This results into an uncontroled termination of the job, before reaching the line where the exception message is printed. As far as I understand the only reason for doing this is to be able to return something before the function execution ends, however the return value is never used in `app/ilp_exact.cpp` and `app/ilp_improve.cpp`. My suggestion is just to make the function `computeIlp` a `void` function and not return anything, so that the catch block just prints the exception message and exits the job gracefully. I have done this in my local copy of the source code, and it works fine, let me know if you approve of this solution and I will submit a pull request.

**Comment by schulzchristian** [comment]
Hi Hayk,

Thank you. Pull rq would be, also please add yourself to the bottom of the
readme file then.

Thanks
Christian
