### ISSUE TITLE
Edge partition numbers

### ISSUE THREAD

**Issue by snash4** [KaHIP/KaHIP#72]
Hi, 
In the input graph file format of metis, only vertex ids are mentioned. 
When we perform the edge_parititioning, it produces a file that lists the block ids of edges to which an edge belongs.
The question, how to map the edge_ids. since no edge ids are given in the input graph.
Example:
input graph
`

7 11
5  3  2
1  3  4
5  4  2  1
2  3  6  7
1  3  6
5  4  7
6  4
`

Produces an edge partition file as:
`

0 
0
0
0
0
1
0
1
0
0
1
1
1
1
0
0
1
1
1
1
1
1
`

**Comment by schulzchristian** [comment]
@DanielSeemaier could you clarify?

**Comment by DanielSeemaier** [comment]
Hi, 
the order is the same as in the input file, i.e., first line is the block of the first edge (edge 1 -> 5 in your example), second line holds the block id of the second edge (1 -> 3) etc.

**Comment by snash4** [comment]
Thanks for the quick response. 
This is for the forward edges. The input graph and 11 edges, and the partition are generated for 22 edges. 
 What is the edge id of reverse edges? 
In the above example, what will the edge id for 5 ->1, and 3 -> 1

Thanks.

**Comment by DanielSeemaier** [comment]
The graph has 11 undirected edges, or 22 directed edges (forward + backward edge). The output file has one line for each directed edge (although forward + backward edges are always be placed in the same partition). In your example, 5 -> 1 is the 15th edge, so its block is 0 (15th line in the output file), the same as 1 -> 5 (first line).

**Comment by snash4** [comment]
The edges belong to the same block whether directed or undirected. i.e 1 -> 5 and  5 -> 1 have same block id. 
In the above example, the first 11 blocks of output file represent the undirected edges in the graph. 
Which means the rest 11 blocks (12th edges onwards)  should have the same block ids. 
But these numbers are different.
First 11 edges have these block ids
`0
0
0
0
0
1
0
1
0
0
1`

The edges 12th onwards has these block ids
`1
1
1
0
0
1
1
1
1
1
1`

ps: how come  5 -> 1 is the 15th edge. 
since 1 -> 5 is 1st edge, 5 -> 1 should be 12th edge, am I right? or I am missing something ?

**Comment by DanielSeemaier** [comment]
In your graph file, each line (except for the first one) contains the neighbors of one node. The first non-header line is 
```
5 3 2
```
which means that node `1` has neighbors `5`, `3`, `2`. Hence, edge 1 is `1 -> 5`, edge 2 is `1 -> 3`, edge 3 is `1 -> 2`. 
The next line is
```
1 3 4
```
which means that node `2` has neighbors `1`, `3`, `4`. Hence, edge 4 is `2 -> 1`, edge 5 is `2 -> 3`, edge 6 is `2 -> 4`. 

etc. etc. etc. 

Therefore, the undirected edge `{1, 2}` is represented by the two undirected edges with ids 3 and 4. So it's not that the first 11 lines in the output file belong to undirected edges and the next 11 lines should mirror them. 

I hope that helps.

**Comment by snash4** [comment]
Got it. I appreciate your help. 
Thanks a lot.
