### ISSUE TITLE
The imbalance parameter is not used in ParHIPPartitionKWay

### ISSUE THREAD

**Issue by IgorBaratta** [KaHIP/KaHIP#74]
In my tests I tried to increase the imbalance for some meshes and I didn't notice any difference.
Looking at the code I realized that the imbalance parameter is not being used in ParHIPPartitionKWay.

But I think it's pretty easy to fix this.

**Comment by schulzchristian** [comment]
Indeed, the imbalance is not set in the interface call. I will fix this asap.

Best
Christian

**Comment by schulzchristian** [comment]
sorry for the delay, should be fixed now.

**Comment by IgorBaratta** [comment]
No problem!
Thanks, again!!
