### ISSUE TITLE
Only Python 3.5 is supported, is there a plan to add support for other python versions?

### ISSUE THREAD

**Issue by ArjunAhuja-git** [KaHIP/KaHIP#76]
Also can you specify the versions of cmake and other modules required for installation?

**Comment by schulzchristian** [comment]
Sure will do. What is the issue with other python versions? Maybe i am able to fix it.

Best
Christian

**Comment by schulzchristian** [comment]
Regarding other python versions, I think you just have to adapt

g++ -O3 -Wall -shared -std=c++11 -fPIC `python3.5 -m pybind11 --includes` kahip.cpp -L../../deploy/ -lkahip -o kahip`python3.5-config --extension-suffix` -Ipybind11/include -I/usr/include/python3.5m/

in the compile_withcmake.sh script. (line 66).

**Comment by schulzchristian** [comment]
I made the script more flexible, now it should work with any python3 version.

Best
Christian
