### ISSUE TITLE
ImportError: libinterface.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ArjunAhuja-git** [KaHIP/KaHIP#77]
While calling python3 callkahipfrompython.py, its strange that I am seeing this error, because I can see the file copied into the deploy folder, any way to fix this error?

**Comment by schulzchristian** [comment]
This should work if you set the path to the lib correctly. (I think its LD_LIBRARY_PATH). 
It should in principle also work if you run it in the deploy folder.

best
Christian

**Comment by ArjunAhuja-git** [comment]
Hi Christian,
  I tried running from deploy folder that that's what produced the error. Can you also check on your end?

**Comment by ArjunAhuja-git** [comment]
But I was able to resolve it after setting LD_LIBRARY_PATH.
