### ISSUE TITLE
Segmentation fault in graph partitioning of Swiss Roll

### ISSUE THREAD

**Issue by ArjunAhuja-git** [KaHIP/KaHIP#78]
I am trying to do graph partitioning of Nearest Neighbour graph of Swiss Roll, the following is the .graph file I have generated:
[outfile.txt](https://github.com/KaHIP/KaHIP/files/6356849/outfile.txt)

This is the command I ran:
 ./deploy/kaffpa ../outfile.graph --k 10  --preconfiguration=strong

Output:
io time: 0.00218797
graph has 1500 nodes and 13500 edges
performing partitioning!
Segmentation fault

**Comment by ArjunAhuja-git** [comment]
I was able to get a partition for k=100 though any recommendation on a how to select min/max k?

**Comment by ArjunAhuja-git** [comment]
Also k=30 takes a lot of time, not sure if its stuck in a loop.

**Comment by schulzchristian** [comment]
Hi,

I ran the graph checker on your input:
*******************************************************************************
KaHIP -- graph format checker.
Output will be given using the IDs from file, i.e. the IDs are starting from 1.
*******************************************************************************
IO done. Now checking the graph .... 
The file does not contain all forward and backward edges. 
Node 2 (line 3) does contain an arc to node 720 but there is no edge (720,2) in the file. 
Please insert this edge in line 721 of the file.


You need to have forward and backward edges in the file.

**Comment by ArjunAhuja-git** [comment]
Strange, ok, I will do that, but why does it succeed for k=100?

**Comment by schulzchristian** [comment]
Because it does not have to crash if you dont specify the graph correctly. Checking the input is generally only done in the graph checker tool.
