### ISSUE TITLE
ParHIP using excessive memory

### ISSUE THREAD

**Issue by kawechel** [KaHIP/KaHIP#79]
I am trying to use ParHIP as part of a large CFD code as an alternative to ParMETIS. The graph I want to partition is 28M vertices and 55M edges - this is a medium sized graph for our application.

I'd like to run the overall simulation on several thousand cores, but unfortunately when using ParHIP the simulation runs out of memory very quickly - I have 128 cores and 256GB RAM per node. I narrowed the issue down to ParHIP itself - I dumped the graph to file and checked with ```graphchecker``` which tells me the graph itself is ok.

I ran a test, scaling ParHIP from 1 to 128 cores, partitioning into 128 parts each time, and measuring the memory high watermark:

![high_watermark](https://user-images.githubusercontent.com/5046256/117872446-93d54c00-b296-11eb-9539-41f14fd57ead.png)

I am using the options ```--k=128 --preconfiguration=fastmesh```. The last datapoint (128 cores) is missing because ParHIP runs out of memory.

Is this expected behaviour? Ideally we would like to be able partition "online" on the same number of cores that we run our simulation on, however I am now wondering if that is not how we are supposed to use ParHIP and whether we will need to partition offline only (something we will implement as well, but we really want both options).

Any guidance would be much appreciated.

**Comment by schulzchristian** [comment]
Hi,

this is not expected. do you use the interface or the commandline? Could you provide the output of the program and if that doesnt help the instance?

Thanks
Christian

**Comment by kawechel** [comment]
Hi,

I first come across the memory use issue using the ParHIP interface and tracking it down to the library rather than our code. However the "high watermark" test above was done using the standalone binary:

```
for N in 1 2 4 8 16 32 64 128
do
   srun -n $N --distribution=block:cyclic --hint=nomultithread parhip ./cam28m.graph --k=128 --preconfiguration=fastmesh
done
```
 
In this case, the binary was buit with HPE/Cray Clang++ and MPICH, however I've also reproduced the issue locally with Intel 2021 versions of C++ and MPI.

The output of a working core count is

```
running collective dummy operations took 0.00126004
took 1.33578
n:28093557 m: 111769122
log> ghost edges 0.0613001
log> local edges 0.9387
upper bound on blocks 226065
log>=====================================
log>============AND WE R DONE============
log>=====================================
log>total partitioning time elapsed 86.4238
log>final edge cut 804805
log>final balance 1.02997
```

but when it runs out of memory this is the output:

**Comment by schulzchristian** [comment]
yes that would certainly help. Do you have the same issue with for example random geometric graphs from the 10th DIMACS implementation challenge -- https://www.cc.gatech.edu/dimacs10/archive/random.shtml? This would help to see in advance if this is something related to your instance. My best guess right now is that for some reason coarsening appears to be broken for you graph. I can certainly check, when I have your graph and see if I can reproduce the error on my system.

Best
Christian

**Comment by schulzchristian** [comment]
and did you try other configurations? e.g. fastsocial?

**Comment by kawechel** [comment]
I have shared a download link with you via email, it should be with you shortly.

I am currently running a test with "fastsocial", which at first glance appears to not suffer from the same memory usage issue, but I will check properly once the whole test has finished.

**Comment by kawechel** [comment]
Ok, I've completed the test using ```fastsocial``` instead of ```fastmesh``` - it's vastly improved, in both memory usage and runtime:
![meshVSsocial](https://user-images.githubusercontent.com/5046256/117968900-9da29200-b31e-11eb-81f9-0e063251fba0.png)
![meshVSsocial-time](https://user-images.githubusercontent.com/5046256/117968907-a004ec00-b31e-11eb-8827-d3d2095ad203.png)

**Comment by schulzchristian** [comment]
I reproduced the problem with fastmesh on my system. I am investigating, but I may only find time next week to look into it. 

Best
Christian

**Comment by kawechel** [comment]
There's no particular rush as I now have a workaround - thanks for pointing it out. Just in case you are interested, I compared the time and memory usage of all 6 modes using 64 cores
![allmodes_time](https://user-images.githubusercontent.com/5046256/117983129-908d9f00-b32e-11eb-8ae3-5e3f5dcc3e2d.png)
![allmodes_memory](https://user-images.githubusercontent.com/5046256/117983136-92576280-b32e-11eb-91e9-97759aee4b0e.png)
As you can see, all the ```mesh``` modes display the same behaviour.

**Comment by schulzchristian** [comment]
Hi, 

so I figured it out already. In the fastmesh, we are limiting cluster sizes during coarsening using a cluster coarsening factor 20000. (line 137 of parallel/parallel_src/parse_parameters.h). That means clusters (if you know the coarsening algorithms that we are using) can only grow to blocksize/20000 nodes. If the graph is ``small'' then the graph is not coarsened at all since the clusters can not grow. On the coarsest level the graph is replicated among all PEs (hence the large memory footprint). This is fine for fastsocial as the coarsening factor is 16, and hence the coarsest level in the hierarchy is very small. I will come up with a more proper parameter for meshes next week. 

Hope this helps!
Christian

**Comment by schulzchristian** [comment]
I issued a quick fix. This should work now, could you please try?

Thanks!
Christian

**Comment by kawechel** [comment]
Thanks for the quick work - I'll add the fix and test. Will let you know how it goes as soon as I can!

**Comment by kawechel** [comment]
I have now tested the fix - in terms of performance it is now getting very close to ```fastsocial``` (~11s vs ~4s on 128 cores ) and memory usage is much better. However it still high enough on large core counts that a simulation using 4 or more nodes would likely OOM (I have not tested this, merely projecting upwards)
![fastmesh-fix_time](https://user-images.githubusercontent.com/5046256/118017107-1d942080-b34e-11eb-8281-96741c4d312f.png)
![fastmesh-fix_mem](https://user-images.githubusercontent.com/5046256/118017112-1f5de400-b34e-11eb-8f74-e0a9841d2e7f.png)

**Comment by schulzchristian** [comment]
Thx for testing! I would suggest you use fastsocial atm, the only different parameter is the cluster coarsening factor and a lower one seems to work much better for you.

Best
Christian

**Comment by kawechel** [comment]
Great - thank you very much for the quick help & fix. :-)
