### ISSUE TITLE
Error when Building KaHIP : "cp: ./build/libinterface.so: No such file or directory"

### ISSUE THREAD

**Issue by sachdevasushant** [KaHIP/KaHIP#82]
Hi Christian,

I am trying to build KaHIP Python module on my mac 11.2.3. It tries to build with AppleClang 11.0.0.11000033.
Almost everything seems to work, except the script is unable to find the shared library at the end.

`./compile_withcmake.sh BUILDPYTHONMODULE`

```
..
[100%] Built target edge_list_to_metis_graph
cp: ./build/libinterface.so: No such file or directory
Undefined symbols for architecture x86_64:
...
```

Help would be appreciated.

**Comment by schulzchristian** [comment]
Hi,

can you send me the whole output?

Thanks
Christian

**Comment by sachdevasushant** [comment]
I'm attaching the entire log.

[kahip_compile.log](https://github.com/KaHIP/KaHIP/files/6642370/kahip_compile.log)

**Comment by schulzchristian** [comment]
This seems to be a problem with pybind. Did you every use pybind on your machine? If not could you try to get a hello world run first? I dont have a mac so i am afraid I can only offer limited help.

Best
Christian

**Comment by DanielSeemaier** [comment]
Hey, 

the first error, `cp: ./build/libinterface.so: No such file or directory`, is unrelated to pybind11: CMake simply names the shared library `libinterface.dylib` on macOS, but the script tries to copy `libinterface.so`. 

For the second error, I was able to build the Python binding on macOS after adding

```
-L/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib -lpython3.9
```

to the g++ call at the end of `compile_withcmake.sh`. 
But I don't know why this isn't needed on Linux or how to avoid hardcoding it.

**Comment by schulzchristian** [comment]
On linux we find them automatically in the .sh file. Maybe the command does not work in MacOS?

**Comment by sachdevasushant** [comment]
Thank you so much @DanielSeemaier. That fix worked, and I was able to compile (after updating the folder to my local folder for the framework!)

**Comment by sachdevasushant** [comment]
Thank you so much for your prompt help, @schulzchristian and @DanielSeemaier !
