### ISSUE TITLE
distributed_edge_partitioning options not working

### ISSUE THREAD

**Issue by snash4** [KaHIP/KaHIP#83]
Hi,
for distributed_edge_partitioning these parameters do not work. 
1. --output_filename

Why distributed_edge_partitioning does not support "strong" preconfiguration.  

Thanks.

**Comment by schulzchristian** [comment]
@DanielSeemaier can you check this? 

Thanks
Christian

**Comment by DanielSeemaier** [comment]
Hey, 

to store the edge partition, use `--save_partition`. I will add a flag to overwrite the default filename. 

The distributed algorithms currently have no "strong" preconfiguration. For best quality, you should use the "ecosocial" preconfiguration. 

Best,
Daniel

**Comment by DanielSeemaier** [comment]
Hey, 

you should now be able to use `--save_partition --output_filename=/some/filename.partition"` to save the edge partition. 

Best,
Daniel
