### ISSUE TITLE
Unable to import kahip in Python

### ISSUE THREAD

**Issue by keving119** [KaHIP/KaHIP#87]
Hi,

I want to use KaHIP in my Python project. For this, I use Ubuntu 20.04 and the latest KaHIP version.
I've ran the commands stated in [the documentation](https://github.com/KaHIP/KaHIP#using-kahip-in-python), however, when I ran the last command to execute the example python file, I get the following error:

```
Traceback (most recent call last):
  File "deploy/callkahipfrompython.py", line 1, in <module>
    import kahip;
ImportError: /KaHIP/deploy/kahip.cpython-38-x86_64-linux-gnu.so: undefined symbol: kaffpa
```

Compiling the code using the `./compile_withcmake.sh BUILDPYTHONMODULE` did not give any errors. What could go wrong here?

**Comment by DanielSeemaier** [comment]
Hi, could you test whether it works with commit caf6bb851a7b10bc877c2b52857ece361cb13ece ? Thanks

**Comment by DanielSeemaier** [comment]
Hi, sorry for the regression. It should now be fixed on master.

**Comment by keving119** [comment]
Hi, thanks for the fast response! It indeed seems to work now :)
