### ISSUE TITLE
Kahip in openmpi cluster

### ISSUE THREAD

**Issue by snash4** [KaHIP/KaHIP#88]
Hi, 
I am not able to run KaHIP distributed edge partitioning in openmpi cluster. 
I can run it on a single machine. 

Can KaHIP run in a cluster?

I receive this error

`WARNING: Open MPI accepted a TCP connection from what appears to be a
another Open MPI process but cannot find a corresponding process
entry for that peer.
This attempted connection will be ignored; your MPI job may or may not
continue properly.
  Local host: abc
  PID:        197798
[abc][[40143,1],3][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[40143,1],2]
[xyz.com:114165] 3 more processes have sent help message help-mpi-btl-openib-cpc-base.txt / no cpcs for port
[xyz.com:114165] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages"`

thanks.

**Comment by schulzchristian** [comment]
Hi, this seems to be a problem with your MPI installation. Did you run a hello world example on your MPI cluster?

Best
Christian

**Comment by snash4** [comment]
HI, 
hello world example works fine.

**Comment by schulzchristian** [comment]
Could you include point to point and maybe broadcast operations in your example? 

Thanks
Christian

**Comment by snash4** [comment]
thanks for pointing out the problem.

the system has multiple interfaces, so had to specify the interface in mpirun.
--mca btl_tcp_if_include eth0
