### ISSUE TITLE
Python - Unexpected outcome of kaffpa function

### ISSUE THREAD

**Issue by keving119** [KaHIP/KaHIP#89]
Hi,

We are trying to get KaHIP working in our Python project and managed to run the example code from `callkahipfrompython.py`.
However, when we run this example, we do not get the output we expect, for some of the cases.

Running the algorithm with `nblocks = 2` or `nblocks =3` makes sense, when looking at the output.
However, when we run the code using `nblocks = 5`, we expect that the algorithm returns 5 different blocks. However, the algorithm outputs `[2,1,4,4,2]`. We interpreted this as 3 different blocks, ( `{0,4},{1},{2,3}` ), is that correct?

Also, we noticed that the imbalance does not seem to have any effect on the output.

At last, in the example code, the list `vwgt` consists of 6 items, while we only have 5 nodes. Does this have any other consequences?

**Comment by schulzchristian** [comment]
The output is not unexpected. A block can indeed be empty. The graph you input is very small. What type of imbalances did you try? If you have five nodes, then the imbalance paramter needs to be very large to have an effect (the bound is (1+epsilon)\lceil |V|/k\rceil).

Best
Christian

**Comment by keving119** [comment]
Thanks for your fast reply.
We saw that the balancing constraint is formulated as: |V_i|<= (1+\epsilon)\lceil|V|/k\rceil. But then, a larger imbalance parameter would only increase the upper bound right? Therefore, we thought it would make sense to make the imbalance parameter as small as possible. But from your reply, I understand that this is incorrect?
Nevertheless, we tried different values for the imbalance parameter (i.e. 0, 0.00001, 0.03, 1, 1000000000), but none of these values changed the outcome of the algorithm.
Could it be that this is because we are using the Python version?

**Comment by schulzchristian** [comment]
Hi Kevin,

I will investigate (may need a couple of days since my work load is quite high atm).
For the imbalance parameter, you are taking the example graph that you specified as input?

Thanks again for reporting!
Christian

**Comment by DanielSeemaier** [comment]
Hey, 

the problem is due to this line: https://github.com/KaHIP/KaHIP/blob/master/lib/partition/initial_partitioning/bipartition.cpp#L167

Say that we have a graph with 3 nodes and that we want a partition with 2 nodes in block 0 and 1 node in block 1. 
Initially, the algorithm places all nodes in block 1 and sets `nodes_left` to 2. After moving one node to block 0, it decrements `nodes_left` to 1 and terminates, producing a partition with 1 node in block 0 and 2 nodes in block 1. 

I'm not sure why we need this check. Seems like we could just remove it or change it to `nodes_left == 0`? 

Anyways, this is probably only a problem for very small toy graphs.

**Comment by keving119** [comment]
Thanks for looking into it!

> For the imbalance parameter, you are taking the example graph that you specified as input?
We are indeed using the example graph from `callkahipfrompython.py`. Here we differed on the mentioned imbalance parameter

**Comment by schulzchristian** [comment]
Hi Kevin, I just looked into it. If you use the strong configuration (mode=3) then the imbalance has indeed an effect on the result. For the fast one, it does not have an impact (I would guess this is random chance, on the small graph really just BFS, e.g. initial partitioning is happening). If you could make the larger graph available to me I can have a look and see if i can help there. I would need the input of the python module e.g. something similar to 

xadj           = [0,2,5,7,9,12];
adjncy         = [1,4,0,2,4,1,3,2,4,0,1,3];
vwgt           = [1,1,1,1,1]
adjcwgt        = [1,1,1,1,1,1,1,1,1,1,1,1]
supress_output = 0
imbalance      = 0.03
nblocks        = 2 
seed           = 0

Does the program behave the same way, when you use it from the command line (e.g. the CLI ./kaffpa) on that graph?

Best
Christian

**Comment by schulzchristian** [comment]
and thanks @DanielSeemaier for investigating

**Comment by keving119** [comment]
Hi Christian, 
Thanks for your fast replies. I am now running the algorithm using the strong mode. 
I did have some struggles finding the right input parameters for `nblocks` and `imbalance`. Most of them resulted in a `segmentation fault` when running in strong mode. Right now, I have seem to find input values that seem to work, as the algorithm is still running. I will keep you updated with the outcome of this run.
Best,
Kevin

**Comment by schulzchristian** [comment]
Hi Kevin,

KaHIP should not crash. My best guess is that the input you provide is not 100% correct. Comman pitfalls: for every forward edge there has to be a backward edge, forward weight has to match backward weight, there can not be selfloops.

Let me know if we can help further.

Best
Christian

**Comment by schulzchristian** [comment]
Another reason may be node numbering: node IDs start from 0 in KaHIP (this also has to be correct for the edge targets).

Best
Christian

**Comment by keving119** [comment]
Thank you Christian for your help. There were still some edges that did not have a backward edge, which caused the problem. I've fixed the input and the output now looks good!
Thanks again for your help and work on the algorithm!
