### ISSUE TITLE
Documentation doesn't specify how to extract edge partitioning.

### ISSUE THREAD

**Issue by TimonKnigge** [KaHIP/KaHIP#90]
In `kahip.pdf` sec 3.2, it is specified that:

> In case of an edge partition, the file contains m lines in which line i constains the block ID of edge i (here the edges are numbered from 0 to m − 1).

But what are these ids? In the case of the DIMACS format, we simply input the adjacency list of the graph, so it is not clear what the ordering of the edge ids is.

**Comment by schulzchristian** [comment]
@DanielSeemaier could you clarify?

**Comment by DanielSeemaier** [comment]
Hey,

the ID of an edge denotes its position in the edges array (`adjncy` array in METIS terminology). For instance, consider the following graph in DIMACS format:

```
n m
2 5 9
1 4 3
...
```

Here, edge 0 is (1, 2); edge 1 is (1, 5); edge 2 is (1; 9), edge 3 is (2, 1); edge 4 is (2, 4); edge 5 is (2, 3) and so on. 

Also have a look at this issue: https://github.com/KaHIP/KaHIP/issues/72

**Comment by TimonKnigge** [comment]
Great, thank you for the quick response!
