### ISSUE TITLE
Missing HyperOrdering?

### ISSUE THREAD

**Issue by mzy2240** [KaHIP/KaHIP#98]
Howdy! I just came across this thesis (https://schulzchristian.github.io/thesis/thesisOleKroeger.pdf) and I am thrilled to see there is finally a new implementation pushing the fill-ins to a new level! According to the thesis, the HyperOrdering method has been implemented and integrated into KaHIP, but I did not find any evidence that the method is available in KaHIP and ready to use. Do you have any plan to release this new method in the near future? Really looking forward to it!!

**Comment by schulzchristian** [comment]
Hi,

Thank you! We are still working on improving the method and afterwards will publicly release it.

Best
Christian

**Comment by mzy2240** [comment]
Any updates on this?

**Comment by schulzchristian** [comment]
No, this probably needs a lot more time. Sorry that i dont have better news for you atm.

Best
Christian
