### ISSUE TITLE
disconnected  results by using KaHIP

### ISSUE THREAD

**Issue by Tiatiaoooo** [KaHIP/KaHIP#99]
This is a very useful graph partition library, but during my experiment, the result of the graph partition can be disconnected (methods I used are Kaffpa, ilp_exact).  How could I avoid the disconnected results?

**Comment by schulzchristian** [comment]
Currently connected partitions (blocks) are not implemented in KaHIP. If you need that in kaffpa, you would have to modify local search such that bridge nodes are not moved. In the ILP solver, you have to add constraints that ensure connectedness. If you are interested in how to do that, send me an email.

Best
Christian
